profile = "user"

change-id = 127866

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"

[llvm]
link-shared = true

[build]
target = [
  "x86_64-unknown-linux-gnu",
]

locked-deps = true
vendor = true
tools = ["cargo", "clippy", "rustfmt", "analysis", "src", "rust-analyzer-proc-macro-srv"]
sanitizers = true
profiler = true
docs = false

[install]
prefix = "/usr"
libdir = "/usr/lib"
bindir = "/usr/bin"

[rust]
codegen-units-std = 1
debuginfo-level = 1
debuginfo-level-std = 2
channel = "stable"
description = "Evolinx"
rpath = false
frame-pointers = true
lld = false
use-lld = "external"
deny-warnings = false
backtrace-on-ice = true
remap-debuginfo = true
jemalloc = true

[dist]
compression-formats = ["xz"]
